server:
  port: 8088

file:
  upload-dir: C:/portfolio-uploads/

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/portfolio
    username: root
    password: 1234
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.portfolio.backend.vo
  configuration:
    map-underscore-to-camel-case: true
